package eagle.entity;
// Generated Jul 7, 2016 4:24:29 PM by Hibernate Tools 4.3.1



/**
 * Eagle generated by hbm2java
 */
public class Eagle  implements java.io.Serializable {


     private Integer id;
     private String eagleType;
     private String eagleSize;
     private String eagleDescription;
     private String countyFound;
     private int locationFound;

    public Eagle() {
    }

    public Eagle(String eagleType, String eagleSize, String eagleDescription, String countyFound, int locationFound) {
       this.eagleType = eagleType;
       this.eagleSize = eagleSize;
       this.eagleDescription = eagleDescription;
       this.countyFound = countyFound;
       this.locationFound = locationFound;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEagleType() {
        return this.eagleType;
    }
    
    public void setEagleType(String eagleType) {
        this.eagleType = eagleType;
    }
    public String getEagleSize() {
        return this.eagleSize;
    }
    
    public void setEagleSize(String eagleSize) {
        this.eagleSize = eagleSize;
    }
    public String getEagleDescription() {
        return this.eagleDescription;
    }
    
    public void setEagleDescription(String eagleDescription) {
        this.eagleDescription = eagleDescription;
    }
    public String getCountyFound() {
        return this.countyFound;
    }
    
    public void setCountyFound(String countyFound) {
        this.countyFound = countyFound;
    }
    public int getLocationFound() {
        return this.locationFound;
    }
    
    public void setLocationFound(int locationFound) {
        this.locationFound = locationFound;
    }




}


